engines:
  tslint:
    enabled: true
    channel: beta
    config: tslint.json
  fixme:
    enabled: true
ratings:
  paths:
    - "**.ts"
exclude_paths:
  - bin
  - node_modules
  - typings
  - coverage
  - lib
